site_information:
  title: ACAP
  description: "Autistic Community Activity Program | Education through recreation"
  logo: /assets/logo.png

navigation_items:
  - label: About
    children: # No URL specified here since it's just a branch node without a page associated with it
      - label: Summer Program
        url: /about/summer.html
      - label: PROJECTS Program
        url: /about/projects.html
      - label: Our History
        url: /about/history.html
  - label: Staff
    children: 
      - label: Our Team
        url: /our-team.html
      - label: Employment
        url: /employment.html
  - label: Enrollment
    children:
    - label: Summer camp
      url: /camp-enrollment.html
    - label: Projects
      url: "/projects-enrollment.html"
  - label: Support
    children:
      - label: Donate
        url: /support/donate.html
      - label: Fundraser
        url: /support/fundraise.html
  - label: "Events"
    url: "/events.html"
